version: 2
jobs:
  build:
    working_directory: /var/www/html
    docker:
      - image: circleci/php:7.2-cli-stretch
        environment:
          APP_ENV: test
    steps:
      - checkout
      - run:
          name: Update Composer
          command: sudo composer self-update
      - run:
          name: Display PHP information
          command: |
            php -v
            php -m
            composer --version
      - restore_cache: # special step to restore the dependency cache if `composer.lock` does not change
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found (See https://circleci.com/docs/2.0/caching/)
            - composer-v1-
      - run:
          name: Install project dependencies
          command: composer install --prefer-dist --optimize-autoloader
      - save_cache: # special step to save the dependency cache with the `composer.lock` cache key template
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run:
          name: Run Unit tests
          command: |
            composer validate
            composer test
